accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comment/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
]

pjt06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

community/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

community/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ('user',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@require_POST
def delete(request, user_pk):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('community:index')

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.
@require_safe
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews,
    }
    return render(request, 'community/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)

@require_safe
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comments.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'community/detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if review.user == request.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('community:index')
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'community/form.html', context)

@require_POST
def delete(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if review.user == request.user:
            review.delete()
    return redirect('community:index')

@require_POST
def create_comment(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
            return redirect('community:detail', review.pk)
        context = {
            'comment_form': comment_form,
            'review': review,
        }
        return render(request, 'community/detail.html', context)
    return HttpResponse(status=401)

@require_POST
def delete_comment(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        else:
            messages.add_message(request, messages.WARNING, '해당 댓글의 작성자만 삭제가 가능합니다.')
        return redirect('community:detail', review_pk)
    return HttpResponse(status=401)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>LOGIN PAGE</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>SIGNUP PAGE</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="회원가입">
  </form>
{% endblock content %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load humanize %}

{% block content %}
  <h1>DETAIL PAGE</h1>
  <hr>
  <p>{{ review.pk }} 번째 리뷰</p>
  <p>리뷰 제목 : {{ review.title }}</p>
  <p>영화 제목 : {{ review.movie_title }}</p>
  <p>영화 등급 : {{ review.rank }}</p>
  <p>영화 내용 : {{ review.content }}</p>
  <p>리뷰작성시간 : {{ review.created_at|naturalday }}</p>
  <p>리뷰수정시간 : {{ review.updated_at|naturaltime }}</p>
  <p>리뷰 작성자 : {{ review.user_id }}</p>
  <hr>
  {% if review.user_id == request.user.pk %}
    <a href="{% url 'community:update' review.pk %}" class="btn btn-info">수정하기</a>
    <form action="{% url 'community:delete' review.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제하기" class="btn btn-danger">
    </form>
    <hr>
  {% endif %}
  {% if comments %}
    <h4>댓글 목록</h4>
    <p>{{ comments|length }} 개의 댓글이 있습니다.</p>
  {% endif %}
  <hr>
  <!-- 댓글 삭제 시 해당 댓글 작성자가 아닐 경우 에러 메세지 -->
  {% if messages %}
      {% for message in messages %}
        <p{% if message.tags %} role="alert" class="alert alert-danger {{ message.tags }}" {% endif %}>
          {{ message }}
        </p>
      {% endfor %}
  {% endif %}
  <!-- 댓글 출력부 -->
  <ul>
    {% for comment in comments %}
      <li>
        {{ comment.user }}의 댓글
        {{ comment }}
        <form action="{% url 'community:delete_comment' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="댓글 삭제">
        </form>
      <hr>
      </li>
      {% empty %}
        <p>아직 댓글이 없습니다.</p>
    {% endfor %}
  </ul>
  <!-- 댓글 작성부 -->
  <form action="{% url 'community:create_comment' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <input type="submit" value="댓글 작성" class="btn btn-info">
  </form>
  <a href="{% url 'community:index' %}">목록으로</a>
{% endblock content %}

community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  {% if request.resolver_match.url_name == 'create' %}
    <h1>CREATE PAGE</h1>
  {% else %}
    <h1>UPDATE PAGE</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

  {% if request.resolver_match.url_name == 'create' %}
    <input type="submit" value="글 작성" class="btn btn-primary">
  {% else %}
    <input type="submit" value="글 수정" class="btn btn-primary">
  {% endif %}
  </form>

  {% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'community:index' %}" class="btn btn-secondary">목록으로</a>
  {% else %}
    <a href="{% url 'community:detail' review.pk %}" class="btn btn-secondary">수정 취소</a>
  {% endif %}

{% endblock content %}

community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX PAGE</h1>
  <hr>
  <a href="{% url 'community:create' %}">[새 리뷰 작성하기]</a>
  <hr>
  {% for review in reviews %}
    <p>{{ review.pk }}번째 리뷰</p>
    <p>{{ review.title }}</p>
    <p>영화 : {{ review.movie_title }}</p>
    <a href="{% url 'community:detail' review.pk %}">자세히</a>
    <hr>
  {% endfor %}
{% endblock content %}

community/templates/community/tmp.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

{% endblock content %}

pjt06/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">
    {% if request.user.is_authenticated %}
      <h3>안녕, {{ request.user }}!</h3>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="로그아웃" class="btn btn-warning">
      </form>
      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="회원 탈퇴" class="btn btn-danger">
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}" class="btn btn-secondary">로그인</a>
      <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원가입</a>
    {% endif %}
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>

pjt06/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">pjt06</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'community:index' %}">전체 리뷰</a>
      </div>
    </div>
  </div>
</nav>